language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.5
  - 5.6
  - 7.0
  - nightly

matrix:
  fast_finish: true

before_install:
  - travis_retry composer self-update
  - travis_retry composer validate

install:
  - travis_retry composer install

script:
  - composer test:travis

after_script:
  - if [[ $TRAVIS_PHP_VERSION != 'nightly' && $TRAVIS_PHP_VERSION != '7.0' ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi
