name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [8.2, 8.3, 8.4, 8.5]
                stability: [prefer-lowest, prefer-stable]
        name: php${{ matrix.php }} - ${{ matrix.stability }}
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
            - uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2
              with:
                php-version: ${{ matrix.php }}
            - id: composer-cache
              run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
            - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
              with:
                path: ~/.composer/cache/files
                key: ${{ matrix.os }}-php-${{ matrix.php }}-composer-${{ matrix.stability }}-${{ hashFiles('**/composer.json') }}
                restore-keys: ${{ matrix.os }}-php-${{ matrix.php }}-composer-${{ matrix.stability }}-
            - run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-suggest
            - run: vendor/bin/phpunit
